require_relative './memcached_test/memcached.rb'
require_relative './memcached_test/memcached_item.rb'
require_relative './memcached_test/server.rb'
require_relative './memcached_test/client.rb'
require_relative './memcached_test/commands_format.rb'